### ISSUE TITLE
Compatibility with brfs transform

### ISSUE THREAD

**Issue by SebastianStamm** [royriojas/persistify#10]
Is there a way to use persistify together with the brfs transform?

If my observations are correct, brfs changes the content of the js file, replacing fs.readFile calls with the inlined file. The result of this transformation is then cached by persistify, so that changes to the inlined file cannot be picked up. The only workaround that I found is to explicitely add files that are transformed by brfs to the neverCache list.

**Comment by royriojas** [comment]
@SebastianStamm yes, you're right. Sadly the only way for it to properly work would be to change the brfs transform to fire an event on the bundle object to let browserify know that a file changed and then discard the cached result for that one. Sadly I haven't had time to investigate how to properly do that. 

For my needs adding the files that use a transform like brfs to the `neverCache` list was good enough. 

:(

**Comment by royriojas** [comment]
So, since the only solution right now for this is to use the `neverCache` list, I would close this issue.
