### ISSUE TITLE
Support for --list

### ISSUE THREAD

**Issue by kasbah** [royriojas/persistify#7]
Would be cool if this supported the `--list` switch of browserify to list dependencies (for Makefiles etc.)

**Comment by royriojas** [comment]
hi @kasbah, Is it supported by watchify? since this tool is just a wrapper over browserify you can actually use browserify directly. Something like this might work

``` bash
./node_modules/browserify/bin/cmd.js --list path/to/your/file.js
```

Will see if I can add it but in the meantime the above line should work (If you're using npm@3 it should just work)

Regards

**Comment by kasbah** [comment]
No, I just checked, it's not supported by watchify. Does calling `cmd.js` give any caching benefit or would it be the same as calling browserify?

**Comment by royriojas** [comment]
The list argument doesn't seem to use any caching information. I might be wrong but I suspect it won't. The most time consuming part in the browserify pipeline are the transforms, figuring out the dependencies doesn't seem to be that time consuming.

**Comment by kasbah** [comment]
The problem I have really is I need to call browserify twice, once to get the list and once to do the actual bundling (this is to integrate with ninja-build depfiles). This triples my build times unfortunately. I guess it's not really a problem of persistify though. But if things were cached in between, it would help.

**Comment by royriojas** [comment]
I see your problem you might use the programatic api in that case.
1. Create a file call `bundler.js` and put the name of your entry, make sure you add any transform you're using.

``` javascript
// bundler.js
var persistify = require( 'persistify' );

var b = persistify( {
  // browserify options here. e.g
  // debug: true
  }, { watch: false } );

b.add( './path/to/your.js' );

b.on( 'bundle:done', function ( time ) {
  setTimeout(function () {  // setTimeout is needed because the cache is verified after the bundling is done using a setTimeout as well, I kinda remember that we need this or an exception was thrown.
   // this is the line you care of. You have here the files needed for the bundle    
   console.log('files', Object.keys(b._options.cache)); // this is the cache of files with the files used in the bundle.
  }, 1);
  console.log( 'time', time );
} );

b.on( 'error', function ( err ) {
  console.log( 'error', err );
} );

// // put your transforms here if using one
// b.transform('babelify');
// b.transform( require( 'shimixify' ).configure( {
//     shims: {
//       jQuery: 'global.jQuery',
//       document: 'global.document',
//       window: 'global.window'
//     }
//   })
// );

function doBundle() {
  b.bundle( function ( err, buff ) {
    if ( err ) {
      throw err;
    }
    require( 'fs' ).writeFileSync( './bundle.js', buff.toString() );
  } );
}

doBundle();
```
1. run it using `node bundler.js`
2. do something with the list of files you have from the process.

**Comment by kasbah** [comment]
Wow, thanks so much. I'll definitely make use of this and probably make little utility package for using browserify/persistify from ninja-build. I think you can close this issue as it's not really a realistic feature request for persistify itself?

**Comment by royriojas** [comment]
sure @kasbah hope this helps.
