### ISSUE TITLE
persistify with envify

### ISSUE THREAD

**Issue by tamascsaba** [royriojas/persistify#9]
If I use persistify with envify, the process.env is cached and not change, when I change it, can persistify detect which file use process.env and never cache it?

**Comment by royriojas** [comment]
hi @tamascsaba 

Trying to make persistify to detect the usage of `process.env` will be highly error prone.

Did you try to ignore the file from cache using [this](https://github.com/royriojas/persistify#my-less-files-are-not-detected-as-changed-when-using-a-transformation-like-lessify-why)

Also, If you use the api you can easily detect which files use process.env and ignore them using the `never-cache` option.

Let me know if this work for you.

**Comment by royriojas** [comment]
Closing for now. Feel free to reopen if the workaround is not enough.
